import re
from datetime import datetime
from sqldoc.extractor import Table, View, StoredProcedure


def _cell(value) -> str:
    """Make a value safe to place inside a Markdown table cell."""
    if value is None:
        return ""
    text = str(value).replace("\r", " ").replace("\n", " ").strip()
    return text.replace("|", "\\|")


def _anchor(heading: str) -> str:
    """Approximate GitHub's heading-to-anchor slug for TOC links."""
    slug = heading.strip().lower()
    slug = re.sub(r"[^\w\s-]", "", slug)   # drop punctuation (incl. the schema dot)
    slug = re.sub(r"\s+", "-", slug)
    return slug


def _fk_actions(col) -> str:
    """Render non-default referential actions, e.g. ' ON DELETE CASCADE'."""
    bits = []
    if getattr(col, "fk_on_delete", None) and col.fk_on_delete != "NO_ACTION":
        bits.append(f"ON DELETE {col.fk_on_delete.replace('_', ' ')}")
    if getattr(col, "fk_on_update", None) and col.fk_on_update != "NO_ACTION":
        bits.append(f"ON UPDATE {col.fk_on_update.replace('_', ' ')}")
    return (" " + ", ".join(bits)) if bits else ""


def _attributes(col) -> str:
    parts = []
    if col.is_primary_key:
        parts.append("PK")
    if col.is_foreign_key:
        parts.append("FK")
        if col.references_table:
            parts.append(f"→ {col.references_table}.{col.references_column}{_fk_actions(col)}")
    if col.is_computed:
        parts.append("computed")
    if getattr(col, "default_definition", None):
        parts.append(f"default {col.default_definition}")
    if col.is_nullable:
        parts.append("nullable")
    return ", ".join(parts)


def _col_description(col) -> str:
    desc = col.description or ""
    if col.is_computed and col.computed_definition:
        desc = (desc + " " if desc else "") + f"(computed: {col.computed_definition})"
    return desc


def render_markdown(database, tables, output_path, views=None, procedures=None):
    views = views or []
    procedures = procedures or []

    total_columns = sum(len(t.columns) for t in tables)
    all_schemas = ({t.schema for t in tables}
                   | {v.schema for v in views}
                   | {p.schema for p in procedures})

    L = []
    L.append(f"# {database} — Database Documentation")
    L.append("")
    L.append(f"_Generated by sqldoc on {datetime.now():%B %d, %Y at %I:%M %p}_")
    L.append("")
    stat_bits = [f"**{len(tables)}** tables"]
    if views:
        stat_bits.append(f"**{len(views)}** views")
    if procedures:
        stat_bits.append(f"**{len(procedures)}** procedures")
    stat_bits.append(f"**{total_columns}** columns")
    stat_bits.append(f"**{len(all_schemas)}** schemas")
    L.append(" · ".join(stat_bits))
    L.append("")

    # --- Table of contents ---
    def toc_for(title, objects):
        if not objects:
            return
        L.append(f"### {title}")
        L.append("")
        for schema in sorted({o.schema for o in objects}):
            names = sorted(o.name for o in objects if o.schema == schema)
            links = ", ".join(f"[{n}](#{_anchor(schema + '.' + n)})" for n in names)
            L.append(f"- **{schema}** — {links}")
        L.append("")

    L.append("## Contents")
    L.append("")
    toc_for("Tables", tables)
    toc_for("Views", views)
    toc_for("Stored Procedures", procedures)

    # --- Tables ---
    L.append("## Tables")
    L.append("")
    for table in sorted(tables, key=lambda t: (t.schema, t.name)):
        L.append(f"### {table.schema}.{table.name}")
        L.append("")
        L.append(f"_{table.row_count:,} rows_")
        L.append("")
        if table.description:
            L.append(table.description.strip())
            L.append("")
        L.append("| Column | Type | Attributes | Description |")
        L.append("| --- | --- | --- | --- |")
        for col in table.columns:
            L.append(f"| {_cell(col.name)} | {_cell(col.data_type)} | {_cell(_attributes(col))} | {_cell(_col_description(col))} |")
        L.append("")
        if table.indexes:
            L.append("**Indexes**")
            L.append("")
            L.append("| Index | Type | Columns |")
            L.append("| --- | --- | --- |")
            for idx in table.indexes:
                flags = "PK" if idx.is_primary_key else ("UNIQUE" if idx.is_unique else "")
                name = f"{idx.name}" + (f" ({flags})" if flags else "")
                cols = ", ".join(idx.key_columns)
                if idx.included_columns:
                    cols += f" (incl: {', '.join(idx.included_columns)})"
                L.append(f"| {_cell(name)} | {_cell(idx.type_desc)} | {_cell(cols)} |")
            L.append("")
        checks = getattr(table, "check_constraints", [])
        uniques = getattr(table, "unique_constraints", [])
        if checks or uniques:
            L.append("**Constraints**")
            L.append("")
            for uq in uniques:
                L.append(f"- UNIQUE **{_cell(uq.name)}** — ({', '.join(uq.columns)})")
            for chk in checks:
                scope = f" on {chk.column}" if chk.column else ""
                L.append(f"- CHECK **{_cell(chk.name)}**{scope} — `{_cell(chk.definition)}`")
            L.append("")
        if table.triggers:
            L.append("**Triggers**")
            L.append("")
            for tg in table.triggers:
                timing = "INSTEAD OF" if tg.is_instead_of else "AFTER"
                meta = f"{timing} {', '.join(tg.events)}" + (" — DISABLED" if tg.is_disabled else "")
                L.append(f"- **{_cell(tg.name)}** — {_cell(meta)}")
                if tg.definition:
                    L.append("")
                    L.append("  <details><summary>Definition</summary>")
                    L.append("")
                    L.append("  ```sql")
                    L.append(tg.definition.strip())
                    L.append("  ```")
                    L.append("")
                    L.append("  </details>")
            L.append("")

    # --- Views ---
    if views:
        L.append("## Views")
        L.append("")
        for view in sorted(views, key=lambda v: (v.schema, v.name)):
            L.append(f"### {view.schema}.{view.name}")
            L.append("")
            if view.description:
                L.append(view.description.strip())
                L.append("")
            if view.columns:
                L.append("| Column | Type | Description |")
                L.append("| --- | --- | --- |")
                for col in view.columns:
                    L.append(f"| {_cell(col.name)} | {_cell(col.data_type)} | {_cell(col.description)} |")
                L.append("")
            if view.definition:
                L.append("<details><summary>Definition</summary>")
                L.append("")
                L.append("```sql")
                L.append(view.definition.strip())
                L.append("```")
                L.append("")
                L.append("</details>")
                L.append("")

    # --- Stored Procedures ---
    if procedures:
        L.append("## Stored Procedures")
        L.append("")
        for proc in sorted(procedures, key=lambda p: (p.schema, p.name)):
            L.append(f"### {proc.schema}.{proc.name}")
            L.append("")
            if proc.description:
                L.append(proc.description.strip())
                L.append("")
            if proc.parameters:
                L.append("| Parameter | Type | Direction |")
                L.append("| --- | --- | --- |")
                for p in proc.parameters:
                    L.append(f"| {_cell(p.name)} | {_cell(p.data_type)} | {'OUTPUT' if p.is_output else 'IN'} |")
                L.append("")
            else:
                L.append("_No parameters._")
                L.append("")
            if proc.definition:
                L.append("<details><summary>Definition</summary>")
                L.append("")
                L.append("```sql")
                L.append(proc.definition.strip())
                L.append("```")
                L.append("")
                L.append("</details>")
                L.append("")

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(L))

    print(f"Documentation written to {output_path}")
