from datetime import datetime
from fpdf import FPDF
from fpdf.fonts import FontFace
from sqldoc.extractor import Table, View, StoredProcedure

# The built-in PDF core fonts are Latin-1 only, so map the handful of non-Latin-1
# characters that realistically show up (AI text, our own arrows) to ASCII and
# drop anything else rather than crash on encoding.
_UNICODE_MAP = {
    "’": "'", "‘": "'", "“": '"', "”": '"',
    "–": "-", "—": "-", "…": "...", "→": "->",
    " ": " ", "•": "*",
}

HEADING_FILL = (243, 244, 246)
HEADING_TEXT = (55, 65, 81)
ACCENT = (79, 70, 229)
MUTED = (107, 114, 128)


def _sanitize(value) -> str:
    if value is None:
        return ""
    text = str(value)
    for uni, asc in _UNICODE_MAP.items():
        text = text.replace(uni, asc)
    return text.encode("latin-1", "replace").decode("latin-1")


def _attributes(col) -> str:
    parts = []
    if col.is_primary_key:
        parts.append("PK")
    if col.is_foreign_key:
        parts.append("FK")
        if col.references_table:
            ref = f"-> {col.references_table}.{col.references_column}"
            if getattr(col, "fk_on_delete", None) and col.fk_on_delete != "NO_ACTION":
                ref += f" ON DELETE {col.fk_on_delete.replace('_', ' ')}"
            if getattr(col, "fk_on_update", None) and col.fk_on_update != "NO_ACTION":
                ref += f" ON UPDATE {col.fk_on_update.replace('_', ' ')}"
            parts.append(ref)
    if col.is_computed:
        parts.append("computed")
    if getattr(col, "default_definition", None):
        parts.append(f"default {col.default_definition}")
    if col.is_nullable:
        parts.append("nullable")
    return ", ".join(parts)


def _col_desc(col) -> str:
    desc = col.description or ""
    if col.is_computed and col.computed_definition:
        desc = (desc + " " if desc else "") + f"(= {col.computed_definition})"
    return desc


class _Doc(FPDF):
    def footer(self):
        self.set_y(-12)
        self.set_font("Helvetica", size=8)
        self.set_text_color(*MUTED)
        self.cell(0, 8, f"Generated by sqldoc  -  page {self.page_no()}/{{nb}}", align="C")


def _table(pdf, headers, rows, widths):
    """Render a bordered data table. `widths` are relative column weights."""
    if not rows:
        return
    pdf.set_font("Helvetica", size=8)
    pdf.set_text_color(0, 0, 0)
    headings_style = FontFace(emphasis="BOLD", fill_color=HEADING_FILL, color=HEADING_TEXT)
    with pdf.table(col_widths=widths, first_row_as_headings=True,
                   headings_style=headings_style, line_height=6,
                   cell_fill_color=(255, 255, 255)) as table:
        head = table.row()
        for h in headers:
            head.cell(_sanitize(h))
        for row in rows:
            r = table.row()
            for cell in row:
                r.cell(_sanitize(cell))
    pdf.ln(2)


def _definition(pdf, sql):
    pdf.set_font("Helvetica", style="B", size=8)
    pdf.set_text_color(*ACCENT)
    pdf.cell(0, 5, "Definition", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Courier", size=7)
    pdf.set_text_color(30, 41, 59)
    pdf.set_fill_color(244, 245, 247)
    pdf.multi_cell(0, 3.6, _sanitize(sql.strip()), fill=True, border=0)
    pdf.ln(2)


def _object_heading(pdf, qualified_name, badge=None):
    pdf.set_font("Helvetica", style="B", size=11)
    pdf.set_text_color(17, 24, 39)
    label = qualified_name + (f"   [{badge}]" if badge else "")
    pdf.cell(0, 7, _sanitize(label), new_x="LMARGIN", new_y="NEXT")


def _section(pdf, title):
    pdf.ln(2)
    pdf.set_font("Helvetica", style="B", size=15)
    pdf.set_text_color(17, 24, 39)
    pdf.cell(0, 9, _sanitize(title), new_x="LMARGIN", new_y="NEXT")


def _schema_heading(pdf, schema):
    pdf.ln(1)
    pdf.set_font("Helvetica", style="B", size=12)
    pdf.set_text_color(*ACCENT)
    pdf.cell(0, 7, _sanitize(schema), new_x="LMARGIN", new_y="NEXT")


def _description(pdf, text):
    if not text:
        return
    pdf.set_font("Helvetica", size=9)
    pdf.set_text_color(75, 85, 99)
    pdf.multi_cell(0, 4.5, _sanitize(text.strip()), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(1)


def _by_schema(objects):
    grouped = {}
    for obj in objects:
        grouped.setdefault(obj.schema, []).append(obj)
    return {s: grouped[s] for s in sorted(grouped)}


def render_pdf(database, tables, output_path, views=None, procedures=None):
    views = views or []
    procedures = procedures or []

    total_columns = sum(len(t.columns) for t in tables)
    all_schemas = ({t.schema for t in tables}
                   | {v.schema for v in views}
                   | {p.schema for p in procedures})

    pdf = _Doc(orientation="P", unit="mm", format="A4")
    pdf.set_auto_page_break(True, margin=16)
    pdf.set_margins(12, 14, 12)
    pdf.alias_nb_pages()
    pdf.add_page()

    # --- Title block ---
    pdf.set_font("Helvetica", style="B", size=22)
    pdf.set_text_color(17, 24, 39)
    pdf.cell(0, 12, _sanitize(f"{database} Database Documentation"), new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", size=10)
    pdf.set_text_color(*MUTED)
    pdf.cell(0, 6, _sanitize(f"Generated by sqldoc on {datetime.now():%B %d, %Y at %I:%M %p}"),
             new_x="LMARGIN", new_y="NEXT")
    stat_bits = [f"{len(tables)} tables"]
    if views:
        stat_bits.append(f"{len(views)} views")
    if procedures:
        stat_bits.append(f"{len(procedures)} procedures")
    stat_bits.append(f"{total_columns} columns")
    stat_bits.append(f"{len(all_schemas)} schemas")
    pdf.set_font("Helvetica", style="B", size=10)
    pdf.set_text_color(*ACCENT)
    pdf.cell(0, 8, _sanitize("  -  ".join(stat_bits)), new_x="LMARGIN", new_y="NEXT")

    # --- Tables ---
    _section(pdf, "Tables")
    for schema, group in _by_schema(tables).items():
        _schema_heading(pdf, schema)
        for table in sorted(group, key=lambda t: t.name):
            _object_heading(pdf, f"{table.schema}.{table.name}", badge=f"{table.row_count:,} rows")
            _description(pdf, table.description)
            _table(pdf,
                   ["Column", "Type", "Attributes", "Description"],
                   [[c.name, c.data_type, _attributes(c), _col_desc(c)] for c in table.columns],
                   widths=(24, 16, 22, 38))
            if table.indexes:
                idx_rows = []
                for idx in table.indexes:
                    flags = "PK" if idx.is_primary_key else ("UNIQUE" if idx.is_unique else "")
                    name = idx.name + (f" ({flags})" if flags else "")
                    cols = ", ".join(idx.key_columns)
                    if idx.included_columns:
                        cols += f" (incl: {', '.join(idx.included_columns)})"
                    idx_rows.append([name, idx.type_desc, cols])
                _table(pdf, ["Index", "Type", "Columns"], idx_rows, widths=(38, 24, 38))
            checks = getattr(table, "check_constraints", [])
            uniques = getattr(table, "unique_constraints", [])
            if checks or uniques:
                con_rows = []
                for uq in uniques:
                    con_rows.append([uq.name, "UNIQUE", "(" + ", ".join(uq.columns) + ")"])
                for chk in checks:
                    con_rows.append([chk.name, "CHECK" + (f" [{chk.column}]" if chk.column else ""),
                                     chk.definition])
                _table(pdf, ["Constraint", "Type", "Definition"], con_rows, widths=(34, 24, 42))
            if table.triggers:
                trg_rows = []
                for tg in table.triggers:
                    timing = "INSTEAD OF" if tg.is_instead_of else "AFTER"
                    trg_rows.append([tg.name + (" (disabled)" if tg.is_disabled else ""),
                                     timing, ", ".join(tg.events)])
                _table(pdf, ["Trigger", "Timing", "Events"], trg_rows, widths=(38, 24, 30))
            pdf.ln(2)

    # --- Views ---
    if views:
        _section(pdf, "Views")
        for schema, group in _by_schema(views).items():
            _schema_heading(pdf, schema)
            for view in sorted(group, key=lambda v: v.name):
                _object_heading(pdf, f"{view.schema}.{view.name}", badge="VIEW")
                _description(pdf, view.description)
                _table(pdf,
                       ["Column", "Type", "Description"],
                       [[c.name, c.data_type, c.description or ""] for c in view.columns],
                       widths=(30, 20, 50))
                if view.definition:
                    _definition(pdf, view.definition)
                pdf.ln(2)

    # --- Stored Procedures ---
    if procedures:
        _section(pdf, "Stored Procedures")
        for schema, group in _by_schema(procedures).items():
            _schema_heading(pdf, schema)
            for proc in sorted(group, key=lambda p: p.name):
                _object_heading(pdf, f"{proc.schema}.{proc.name}", badge="PROC")
                _description(pdf, proc.description)
                if proc.parameters:
                    _table(pdf,
                           ["Parameter", "Type", "Direction"],
                           [[p.name, p.data_type, "OUTPUT" if p.is_output else "IN"] for p in proc.parameters],
                           widths=(40, 30, 20))
                if proc.definition:
                    _definition(pdf, proc.definition)
                pdf.ln(2)

    pdf.output(output_path)
    print(f"Documentation written to {output_path}")
