"""Scheduled weekly email digest for the agent.

When `agent.weekly_report` is enabled, the daemon emails a formatted HTML digest
on the configured weekday/hour (default Monday 08:00 local) covering the past
week for every monitored database: schema changes, newly-exposed PII, health
trends, SQL Agent job failures, and infrastructure/security alerts.

The digest is built purely from what the agent already records in its store
(the event timeline + the metrics time-series), so no extra database access is
needed to produce it. Scheduling is idempotent — `maybe_send_weekly_report`
sends at most one digest per calendar week, tracked via a `kv` marker.
"""
from datetime import datetime, timedelta, timezone

from sqldoc import __version__
from sqldoc.agent import notify as notify_mod

# Event types that are security / infrastructure alerts (grouped in the digest).
INFRA_ALERT_TYPES = ("disk_low", "errorlog_critical", "linked_server_down",
                     "backup_stale", "replica_lag", "tempdb_version_store", "nl_alert")

_LAST_SENT_KEY = "weekly_report_last_sent"


def _iso(dt) -> str:
    return dt.replace(microsecond=0).isoformat()


def _delta(first, last, field):
    if first and last and first.get(field) is not None and last.get(field) is not None:
        return last[field] - first[field]
    return None


def _db_section(store, db_name, since_iso):
    events = store.events_since(since_iso, db_name)
    by_type = {}
    for e in events:
        by_type.setdefault(e["type"], []).append(e)
    metrics = store.metrics_since(since_iso, db_name)
    first = metrics[0] if metrics else None
    last = metrics[-1] if metrics else None
    infra = [e for e in events if e["type"] in INFRA_ALERT_TYPES]
    return {
        "name": db_name,
        "schema_changes": by_type.get("schema_change", []),
        "new_pii": by_type.get("new_pii", []),
        "job_failures": by_type.get("job_failure", []),
        "health_degradations": by_type.get("health_degradation", []),
        "infra_alerts": infra,
        "pii_score_delta": _delta(first, last, "pii_score"),
        "health_delta": _delta(first, last, "health_issues"),
        "pii_high_now": last["pii_high"] if last else None,
        "health_now": last["health_issues"] if last else None,
        "polls": len(metrics),
        "total_events": len(events),
    }


def build_weekly_digest(store, db_names, since_iso, generated_at_iso):
    sections = [_db_section(store, n, since_iso) for n in db_names]
    totals = {
        "schema_changes": sum(len(s["schema_changes"]) for s in sections),
        "new_pii": sum(len(s["new_pii"]) for s in sections),
        "job_failures": sum(len(s["job_failures"]) for s in sections),
        "infra_alerts": sum(len(s["infra_alerts"]) for s in sections),
        "databases": len(sections),
    }
    return {"since": since_iso, "generated_at": generated_at_iso,
            "databases": sections, "totals": totals}


# --- rendering --------------------------------------------------------------

def _trend_text(delta, lower_is_better=True):
    if delta is None:
        return "no data"
    if delta == 0:
        return "no change"
    worse = (delta > 0) if lower_is_better else (delta < 0)
    word = "worse" if worse else "improved"
    return f"{'+' if delta > 0 else ''}{delta} ({word})"


def render_weekly_text(digest) -> str:
    t = digest["totals"]
    lines = [
        "sqldoc weekly digest",
        f"Week ending {digest['generated_at']}",
        "",
        f"Across {t['databases']} database(s): {t['schema_changes']} schema change(s), "
        f"{t['new_pii']} new-PII event(s), {t['job_failures']} job failure(s), "
        f"{t['infra_alerts']} infrastructure/security alert(s).",
        "",
    ]
    for s in digest["databases"]:
        lines.append(f"== {s['name']} ==")
        lines.append(f"  Schema changes:      {len(s['schema_changes'])}")
        lines.append(f"  New PII findings:    {len(s['new_pii'])}  "
                     f"(HIGH now: {s['pii_high_now']}, score trend {_trend_text(s['pii_score_delta'])})")
        lines.append(f"  Health issues now:   {s['health_now']}  "
                     f"(trend {_trend_text(s['health_delta'])})")
        lines.append(f"  Job failures:        {len(s['job_failures'])}")
        lines.append(f"  Infra/security:      {len(s['infra_alerts'])}")
        lines.append("")
    lines.append(f"Generated by sqldoc v{__version__}.")
    return "\n".join(lines)


_HTML = """<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>sqldoc weekly digest</title></head>
<body style="margin:0;background:#0a0a0f;color:#e5e7eb;font-family:-apple-system,Segoe UI,Roboto,sans-serif;">
<div style="max-width:720px;margin:0 auto;padding:28px 20px;">
  <div style="font-size:0.72rem;letter-spacing:0.2em;text-transform:uppercase;color:#94a3b8;">sqldoc &middot; Weekly digest</div>
  <h1 style="font-size:1.6rem;color:#f8fafc;margin:8px 0 4px;">Week ending {generated}</h1>
  <p style="color:#94a3b8;font-size:0.9rem;margin:0 0 22px;">
    Across {n_db} database(s): <b style="color:#e5e7eb;">{t_schema}</b> schema change(s),
    <b style="color:#e5e7eb;">{t_pii}</b> new-PII event(s),
    <b style="color:#e5e7eb;">{t_jobs}</b> job failure(s),
    <b style="color:#e5e7eb;">{t_infra}</b> infra/security alert(s).
  </p>
  {cards}
  <div style="color:#64748b;font-size:0.76rem;margin-top:28px;text-align:center;">
    Generated by sqldoc v{version}. You are receiving this because weekly_report is enabled in your agent config.
  </div>
</div>
</body></html>"""

_CARD = """<div style="background:#1e2530;border:1px solid #2a3340;border-radius:12px;padding:18px 22px;margin-bottom:14px;">
  <div style="font-size:1.05rem;font-weight:700;color:#f8fafc;margin-bottom:12px;">{name}</div>
  <table style="width:100%;border-collapse:collapse;font-size:0.88rem;">
    <tr><td style="color:#94a3b8;padding:4px 0;">Schema changes</td><td style="text-align:right;color:#e5e7eb;">{schema}</td></tr>
    <tr><td style="color:#94a3b8;padding:4px 0;">New PII findings</td><td style="text-align:right;color:{pii_color};">{pii} &nbsp; <span style="color:#64748b;">HIGH now {pii_high}, {pii_trend}</span></td></tr>
    <tr><td style="color:#94a3b8;padding:4px 0;">Health issues (now)</td><td style="text-align:right;color:#e5e7eb;">{health_now} &nbsp; <span style="color:#64748b;">{health_trend}</span></td></tr>
    <tr><td style="color:#94a3b8;padding:4px 0;">Job failures</td><td style="text-align:right;color:{jobs_color};">{jobs}</td></tr>
    <tr><td style="color:#94a3b8;padding:4px 0;">Infra / security alerts</td><td style="text-align:right;color:{infra_color};">{infra}</td></tr>
  </table>
</div>"""


def _hot(n):
    return "#f87171" if n else "#e5e7eb"


def render_weekly_html(digest) -> str:
    cards = []
    for s in digest["databases"]:
        cards.append(_CARD.format(
            name=_esc(s["name"]),
            schema=len(s["schema_changes"]),
            pii=len(s["new_pii"]), pii_color=_hot(len(s["new_pii"])),
            pii_high=s["pii_high_now"], pii_trend=_trend_text(s["pii_score_delta"]),
            health_now=s["health_now"], health_trend=_trend_text(s["health_delta"]),
            jobs=len(s["job_failures"]), jobs_color=_hot(len(s["job_failures"])),
            infra=len(s["infra_alerts"]), infra_color=_hot(len(s["infra_alerts"]))))
    t = digest["totals"]
    return _HTML.format(
        generated=_esc(digest["generated_at"]), n_db=t["databases"],
        t_schema=t["schema_changes"], t_pii=t["new_pii"], t_jobs=t["job_failures"],
        t_infra=t["infra_alerts"], cards="\n".join(cards), version=__version__)


def _esc(s):
    return (str(s).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"))


# --- scheduling -------------------------------------------------------------

def _week_key(dt) -> str:
    """ISO year-week string, e.g. '2026-W28' — the idempotency key for a week."""
    iso = dt.isocalendar()
    return f"{iso[0]}-W{iso[1]:02d}"


def is_due(weekly_cfg, now, last_week_key) -> bool:
    """True when a digest should be sent now: it's the configured weekday at/after
    the configured hour, and we haven't already sent one this calendar week."""
    if not weekly_cfg or not weekly_cfg.enabled:
        return False
    if now.weekday() != weekly_cfg.weekday:
        return False
    if now.hour < weekly_cfg.hour:
        return False
    return _week_key(now) != last_week_key


def maybe_send_weekly_report(store, agent_config, now=None, log=lambda *_: None,
                             send_fn=None) -> bool:
    """If a weekly digest is due, build + email it and record the send. Returns
    True if a digest was sent. Safe to call frequently (idempotent per week)."""
    weekly = getattr(agent_config, "weekly_report", None)
    if not weekly or not weekly.enabled:
        return False
    smtp = getattr(agent_config.notify, "smtp", None)
    if not smtp:
        return False
    now = now or datetime.now()
    last = store.get_meta(_LAST_SENT_KEY)
    if not is_due(weekly, now, last):
        return False

    since_iso = _iso((datetime.now(timezone.utc) - timedelta(days=7)))
    db_names = [d.name for d in agent_config.databases]
    digest = build_weekly_digest(store, db_names, since_iso, now.strftime("%B %d, %Y"))
    html = render_weekly_html(digest)
    text = render_weekly_text(digest)
    subject = f"[sqldoc] Weekly digest - {now.strftime('%b %d, %Y')}"

    send = send_fn or notify_mod.send_html_email
    try:
        send(smtp, subject, html, text)
        store.set_meta(_LAST_SENT_KEY, _week_key(now))
        log(f"weekly digest emailed for {len(db_names)} database(s)")
        return True
    except Exception as e:
        log(f"weekly digest failed: {type(e).__name__}: {e}")
        return False
