{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sqldoc.fullname" . }}-config
  labels:
    {{- include "sqldoc.labels" . | nindent 4 }}
type: Opaque
stringData:
  .sqldoc.yml: |
{{ .Values.config | indent 4 }}
{{- end }}
