"""Confluence Cloud integration via REST API v2 (API-token / basic auth).

Maintains one living page per database under a configured space + parent page:
the executive scores, a PII-findings table, a health summary, and documentation
stats are rendered as native Confluence storage-format content, and the full
rendered HTML reports are attached to the page. Re-pushing updates the same page
(matched by title) in place rather than creating duplicates.

Config (``confluence:`` in .sqldoc.yml)::

    confluence:
      base_url: https://acme.atlassian.net/wiki
      email: bot@acme.com
      api_token: "***"
      space_key: DBDOCS
      parent_page_id: "123456"       # optional
      title_prefix: "Database: "     # optional
"""
import html

from sqldoc.integrations.base import IntegrationError, need, result


def _base(cfg) -> str:
    b = (cfg.get("base_url") or "").rstrip("/")
    if not b:
        raise IntegrationError("confluence.base_url is required (e.g. https://acme.atlassian.net/wiki).")
    return b


def api_request(method: str, url: str, cfg: dict, *, timeout: float = 30.0, **kwargs):
    """Confluence REST call with API-token basic auth; raises on non-2xx."""
    import requests
    auth = (cfg["email"], cfg["api_token"])
    headers = kwargs.pop("headers", {})
    headers.setdefault("Accept", "application/json")
    resp = requests.request(method, url, auth=auth, headers=headers, timeout=timeout, **kwargs)
    if not (200 <= resp.status_code < 300):
        raise IntegrationError(
            f"Confluence {method} {url} -> {resp.status_code}: {resp.text[:300]}")
    if resp.content and resp.headers.get("Content-Type", "").startswith("application/json"):
        return resp.json()
    return {}


def resolve_space_id(cfg) -> str:
    data = api_request("GET", f"{_base(cfg)}/api/v2/spaces", cfg,
                       params={"keys": cfg["space_key"], "limit": 1})
    results = data.get("results", [])
    if not results:
        raise IntegrationError(
            f"Confluence space '{cfg['space_key']}' not found (check space_key + permissions).")
    return str(results[0]["id"])


def find_page(cfg, space_id, title):
    """Return (page_id, version_number) for an existing page with this title in
    the space, or (None, None)."""
    data = api_request("GET", f"{_base(cfg)}/api/v2/pages", cfg,
                       params={"space-id": space_id, "title": title, "limit": 1,
                               "body-format": "storage"})
    for page in data.get("results", []):
        if page.get("title") == title:
            ver = (page.get("version") or {}).get("number", 1)
            return str(page["id"]), int(ver)
    return None, None


def _table(headers, rows) -> str:
    head = "".join(f"<th>{html.escape(str(h))}</th>" for h in headers)
    body = "".join(
        "<tr>" + "".join(f"<td>{html.escape('' if c is None else str(c))}</td>" for c in row) + "</tr>"
        for row in rows)
    return f"<table><tbody><tr>{head}</tr>{body}</tbody></table>"


def build_storage_body(bundle, metrics) -> str:
    """Render the bundle as Confluence storage-format XHTML."""
    from sqldoc.pii import summarize as pii_summarize
    m = metrics or {}
    parts = ["<p><em>Generated by sqldoc.</em></p>"]

    # Executive scorecard.
    def _score(v):
        return "N/A" if v is None else str(v)
    parts.append("<h2>Executive scorecard</h2>")
    parts.append(_table(
        ["Overall", "Data protection", "Backups", "Security", "Performance"],
        [[_score(m.get("overall_score")), _score(m.get("pii_safety_score")),
          (None if m.get("backup_compliance_pct") is None else f"{m['backup_compliance_pct']}%"),
          _score(m.get("security_score")), _score(m.get("health_score"))]]))

    # Documentation stats.
    parts.append("<h2>Documentation</h2>")
    parts.append(_table(
        ["Tables", "Views", "Procedures", "Sensitive columns"],
        [[len(bundle.tables), len(bundle.views), len(bundle.procedures), len(bundle.findings)]]))

    # PII findings.
    pii = pii_summarize(bundle.findings)
    parts.append("<h2>PII / compliance findings</h2>")
    parts.append(f"<p>{pii['total']} finding(s) across {pii['tables_affected']} table(s): "
                 f"{pii['by_risk'].get('HIGH', 0)} HIGH, {pii['by_risk'].get('MEDIUM', 0)} MEDIUM, "
                 f"{pii['by_risk'].get('LOW', 0)} LOW.</p>")
    if bundle.findings:
        ordered = sorted(bundle.findings,
                         key=lambda f: ({"HIGH": 0, "MEDIUM": 1, "LOW": 2}.get(f.risk, 3),
                                        f.schema, f.table, f.column))[:200]
        parts.append(_table(
            ["Column", "Category", "Risk", "Regulations", "Action"],
            [[f"{f.schema}.{f.table}.{f.column}", f.category, f.risk,
              ", ".join(f.regulations or []), getattr(f, "action", "")] for f in ordered]))
        if len(bundle.findings) > 200:
            parts.append(f"<p><em>(+{len(bundle.findings) - 200} more — see the attached PII report.)</em></p>")

    # Health summary.
    if bundle.health_summary:
        hs = bundle.health_summary
        parts.append("<h2>Health summary</h2>")
        parts.append(_table(
            ["Slow queries", "Dead tables", "Missing indexes", "Fragmented", "Total issues"],
            [[hs.get("slow_queries"), hs.get("dead_tables"), hs.get("missing_indexes"),
              hs.get("fragmented_indexes"), hs.get("issues")]]))

    parts.append("<p><em>Full HTML reports are attached to this page.</em></p>")
    return "".join(parts)


class Client:
    def __init__(self, config: dict):
        self.cfg = config or {}

    def _need(self):
        need(self.cfg, "base_url", "email", "api_token", "space_key",
             integration="confluence")

    def _title(self, database) -> str:
        return f"{self.cfg.get('title_prefix', 'Database: ')}{database}"

    def test(self) -> dict:
        self._need()
        space_id = resolve_space_id(self.cfg)
        return result(True, f"Connected to Confluence space '{self.cfg['space_key']}' "
                            f"(id {space_id}).", space_id=space_id)

    def _upsert_page(self, space_id, title, body):
        page_id, version = find_page(self.cfg, space_id, title)
        payload = {
            "spaceId": space_id,
            "status": "current",
            "title": title,
            "body": {"representation": "storage", "value": body},
        }
        if page_id:
            payload["id"] = page_id
            payload["version"] = {"number": version + 1, "message": "sqldoc update"}
            api_request("PUT", f"{_base(self.cfg)}/api/v2/pages/{page_id}", self.cfg,
                        headers={"Content-Type": "application/json"}, json=payload)
            return page_id, False
        if self.cfg.get("parent_page_id"):
            payload["parentId"] = str(self.cfg["parent_page_id"])
        created = api_request("POST", f"{_base(self.cfg)}/api/v2/pages", self.cfg,
                              headers={"Content-Type": "application/json"}, json=payload)
        return str(created["id"]), True

    def _attach(self, page_id, artifacts):
        # Attachments use the v1 content API (v2 has no create-attachment yet); the
        # same token works. X-Atlassian-Token defeats XSRF checks.
        for art in artifacts:
            if not art.name.endswith((".html", ".pdf")):
                continue
            api_request(
                "PUT", f"{_base(self.cfg)}/rest/api/content/{page_id}/child/attachment",
                self.cfg, headers={"X-Atlassian-Token": "no-check"},
                params={"allowDuplicated": "true"},
                files={"file": (art.name, art.content, art.mime)})

    def push_reports(self, artifacts, metrics=None, bundle=None) -> dict:
        self._need()
        if bundle is None:
            raise IntegrationError("Confluence push needs the collected bundle.")
        space_id = resolve_space_id(self.cfg)
        title = self._title(bundle.database)
        body = build_storage_body(bundle, metrics)
        page_id, created = self._upsert_page(space_id, title, body)
        try:
            self._attach(page_id, artifacts)
            attached = True
        except IntegrationError:
            attached = False   # page still updated; attachment is best-effort
        url = f"{_base(self.cfg)}/spaces/{self.cfg['space_key']}/pages/{page_id}"
        verb = "Created" if created else "Updated"
        note = "" if attached else " (attachments skipped)"
        return result(True, f"{verb} Confluence page '{title}'{note}.", url=url, page_id=page_id)
