"""Notion integration via the official REST API (internal integration token).

On --push, per database:

* a **doc page** is created under ``parent_page_id`` with the executive
  scorecard, documentation stats, and a health summary as native Notion blocks
  (an existing same-titled page is archived first, so re-push updates in place);
* a child **"PII Findings" database** is created under that page with one row per
  sensitive column (Column / Category / Risk / Regulations / Action);
* if a metrics-tracker ``database_id`` is configured, a row for this database is
  upserted there with the health/PII/security scores **as Notion properties**.

Config (``notion:`` in .sqldoc.yml)::

    notion:
      token: "secret_***"
      parent_page_id: "<page-id>"      # where doc pages are created
      database_id: "<database-id>"     # optional metrics tracker to upsert into

Every HTTP call goes through the module-level ``notion_request`` (mockable).
"""
import datetime

from sqldoc.integrations.base import IntegrationError, need, result

API = "https://api.notion.com/v1"
_VERSION = "2022-06-28"


def notion_request(method: str, path: str, cfg: dict, *, timeout: float = 30.0, **kwargs):
    """Call the Notion API (path relative to /v1); raise IntegrationError on non-2xx."""
    import requests
    url = f"{API}{path}"
    headers = kwargs.pop("headers", {})
    headers.setdefault("Authorization", f"Bearer {cfg['token']}")
    headers.setdefault("Notion-Version", _VERSION)
    resp = requests.request(method, url, headers=headers, timeout=timeout, **kwargs)
    if not (200 <= resp.status_code < 300):
        raise IntegrationError(f"Notion {method} {path} -> {resp.status_code}: {resp.text[:300]}")
    return resp.json() if resp.content else {}


# --- block / property helpers ----------------------------------------------

def _rt(text):
    return [{"type": "text", "text": {"content": str(text)[:2000]}}]


def _heading(text):
    return {"object": "block", "type": "heading_2",
            "heading_2": {"rich_text": _rt(text)}}


def _bullet(text):
    return {"object": "block", "type": "bulleted_list_item",
            "bulleted_list_item": {"rich_text": _rt(text)}}


def _para(text):
    return {"object": "block", "type": "paragraph",
            "paragraph": {"rich_text": _rt(text)}}


def _score(v):
    return "N/A" if v is None else str(v)


def build_blocks(bundle, metrics) -> list:
    m = metrics or {}
    blocks = [
        _para("Generated by sqldoc."),
        _heading("Executive scorecard"),
        _bullet(f"Overall: {_score(m.get('overall_score'))}"),
        _bullet(f"Data protection: {_score(m.get('pii_safety_score'))}"),
        _bullet(f"Backups: {('N/A' if m.get('backup_compliance_pct') is None else str(m['backup_compliance_pct']) + '%')}"),
        _bullet(f"Security: {_score(m.get('security_score'))}"),
        _bullet(f"Performance: {_score(m.get('health_score'))}"),
        _heading("Documentation"),
        _bullet(f"Tables: {len(bundle.tables)}"),
        _bullet(f"Views: {len(bundle.views)}"),
        _bullet(f"Procedures: {len(bundle.procedures)}"),
        _bullet(f"Sensitive columns: {len(bundle.findings)}"),
    ]
    if bundle.health_summary:
        hs = bundle.health_summary
        blocks.append(_heading("Health summary"))
        blocks.append(_bullet(f"Slow queries: {hs.get('slow_queries')}"))
        blocks.append(_bullet(f"Missing indexes: {hs.get('missing_indexes')}"))
        blocks.append(_bullet(f"Total issues: {hs.get('issues')}"))
    return blocks


def _num(v):
    return {"number": v if isinstance(v, (int, float)) else None}


def metric_properties(metrics) -> dict:
    """Health/PII/security scores as Notion database properties for the tracker."""
    m = metrics or {}
    return {
        "Name": {"title": _rt(m.get("database", ""))},
        "PII High": _num(m.get("pii_high")),
        "PII Findings": _num(m.get("pii_findings")),
        "Security Score": _num(m.get("security_score")),
        "Health Score": _num(m.get("health_score")),
        "Backup %": _num(m.get("backup_compliance_pct")),
        "Overall": _num(m.get("overall_score")),
        "Scan Date": {"date": {"start": datetime.date.today().isoformat()}},
    }


class Client:
    def __init__(self, config: dict):
        self.cfg = config or {}

    def test(self) -> dict:
        need(self.cfg, "token", integration="notion")
        me = notion_request("GET", "/users/me", self.cfg)
        name = me.get("name") or me.get("bot", {}).get("owner", {}).get("type", "integration")
        return result(True, f"Connected to Notion as '{name}'.", bot=name)

    # --- doc page + findings db --------------------------------------------

    def _archive_existing(self, title):
        """Best-effort: archive an existing doc page with this title under the
        parent, so re-push doesn't pile up duplicates."""
        try:
            data = notion_request("POST", "/search", self.cfg,
                                  json={"query": title,
                                        "filter": {"property": "object", "value": "page"}})
        except IntegrationError:
            return
        parent = str(self.cfg.get("parent_page_id"))
        for page in data.get("results", []):
            pp = page.get("parent", {})
            if str(pp.get("page_id")) == parent and _page_title(page) == title:
                try:
                    notion_request("PATCH", f"/pages/{page['id']}", self.cfg,
                                  json={"archived": True})
                except IntegrationError:
                    pass

    def _create_doc_page(self, bundle, metrics):
        title = bundle.database
        self._archive_existing(title)
        page = notion_request("POST", "/pages", self.cfg, json={
            "parent": {"type": "page_id", "page_id": str(self.cfg["parent_page_id"])},
            "properties": {"title": {"title": _rt(title)}},
            "children": build_blocks(bundle, metrics),
        })
        return page["id"], page.get("url")

    def _create_findings_db(self, page_id, findings):
        db = notion_request("POST", "/databases", self.cfg, json={
            "parent": {"type": "page_id", "page_id": page_id},
            "title": _rt("PII Findings"),
            "properties": {
                "Column": {"title": {}},
                "Category": {"rich_text": {}},
                "Risk": {"select": {"options": [
                    {"name": "HIGH", "color": "red"},
                    {"name": "MEDIUM", "color": "orange"},
                    {"name": "LOW", "color": "yellow"}]}},
                "Regulations": {"rich_text": {}},
                "Action": {"rich_text": {}},
            },
        })
        db_id = db["id"]
        for f in findings[:100]:
            notion_request("POST", "/pages", self.cfg, json={
                "parent": {"database_id": db_id},
                "properties": {
                    "Column": {"title": _rt(f"{f.schema}.{f.table}.{f.column}")},
                    "Category": {"rich_text": _rt(f.category)},
                    "Risk": {"select": {"name": f.risk}},
                    "Regulations": {"rich_text": _rt(", ".join(f.regulations or []))},
                    "Action": {"rich_text": _rt(getattr(f, "action", "") or "")},
                },
            })
        return db_id, len(findings[:100])

    def _upsert_tracker_row(self, metrics):
        db_id = self.cfg["database_id"]
        title = metrics.get("database", "")
        found = notion_request("POST", f"/databases/{db_id}/query", self.cfg, json={
            "filter": {"property": "Name", "title": {"equals": title}}, "page_size": 1})
        props = metric_properties(metrics)
        results = found.get("results", [])
        if results:
            notion_request("PATCH", f"/pages/{results[0]['id']}", self.cfg,
                          json={"properties": props})
            return "updated"
        notion_request("POST", "/pages", self.cfg,
                      json={"parent": {"database_id": db_id}, "properties": props})
        return "created"

    def push_reports(self, artifacts, metrics=None, bundle=None) -> dict:
        need(self.cfg, "token", "parent_page_id", integration="notion")
        if bundle is None:
            raise IntegrationError("Notion push needs the collected bundle.")
        page_id, url = self._create_doc_page(bundle, metrics)
        _, n = self._create_findings_db(page_id, bundle.findings)
        tracked = ""
        if self.cfg.get("database_id"):
            state = self._upsert_tracker_row(metrics or {})
            tracked = f"; tracker row {state}"
        return result(True, f"Published Notion doc page for '{bundle.database}' with "
                            f"{n} PII finding(s){tracked}.", url=url, page_id=page_id)


def _page_title(page) -> str:
    """Extract the plain-text title from a Notion page object."""
    for prop in (page.get("properties") or {}).values():
        if prop.get("type") == "title":
            return "".join(t.get("plain_text", t.get("text", {}).get("content", ""))
                           for t in prop.get("title", []))
    return ""
